### ISSUE TITLE
Add .gitignore to ignore object files

### ISSUE THREAD

**Issue by katp32** [smcameron/open-simplex-noise-in-c#13]
This is a really trivial and nitpicky issue I know, but it would be convenient if the repository had a gitignore to ignore compiled object files. Otherwise, when using this repo as a submodule in a larger project, compiled objects will always be shown as untracked files when using `git status`.

**Comment by smcameron** [comment]
Fixed by d252201865b91b4d9cdf662fd00ab15ea58f551a
