### ISSUE TITLE
What an amazing Library!

### ISSUE THREAD

**Issue by SEGenjoysBlivits** [smcameron/open-simplex-noise-in-c#16]
Hi, I've been looking for something like this for hours but this really sticks out. I love how easy it is to use and how well it works. This will definitely come in handy while making my indie game which might appear on GitHub in the next few weeks. This project is very deserving of you being credited in the about section of my game. Best regards.

**Comment by smcameron** [comment]
Well, it's really just a straightforward port of Kurt Spencer's open simplex noise from java to C: https://gist.github.com/KdotJPG/b1270127455a94ac5d19

FWIW, godot used a variant of this code for awhile: https://github.com/godotengine/godot/commit/f12a1b88636f6147d2445749d728ecd9585bc3c4

until it was replaced by fastnoise: https://github.com/godotengine/godot/commit/862296273b3f446f4bbcfc5ea682a866ffe1ebcf
