### ISSUE TITLE
Spurious assignments

### ISSUE THREAD

**Issue by stolk** [smcameron/open-simplex-noise-in-c#4]
There are quite a few assignments in the code that appear to have no use.

/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:678:5: warning: Value stored to 'aScore' is never read
                                aScore = score;
                                ^        ~~~~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:682:5: warning: Value stored to 'bScore' is never read
                                bScore = score;
                                ^        ~~~~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:689:5: warning: Value stored to 'aScore' is never read
                                aScore = score;
                                ^        ~~~~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:693:5: warning: Value stored to 'bScore' is never read
                                bScore = score;
                                ^        ~~~~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:1429:4: warning: Value stored to 'bScore' is never read
                        bScore = p4;
                        ^        ~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:1433:4: warning: Value stored to 'aScore' is never read
                        aScore = p4;
                        ^        ~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:1858:4: warning: Value stored to 'bScore' is never read
                        bScore = p4;
                        ^        ~~
/Users/bram/apps/Proto/Dig/Dig/open-simplex-noise.c:1862:4: warning: Value stored to 'aScore' is never read
                        aScore = p4;
                        ^        ~~
8 warnings generated.

**Comment by katp32** [comment]
Invoking the Clang static analyzer with `clang --analyze open-simplex-noise.c` produces similar output, albeit with different line numbers, likely due to changes to the code since 2014.

On lines 700, 704, 711, and 715, `aScore` or `bScore` are set, but neither is used again in the remainder of `open_simplex_noise3`, so the assignment is indeed spurious.

The static analyzer also complains about lines 1467, 1471, 1891, and 1895, however that function is significantly longer and I've not had time to look at it it yet.

**Comment by smcameron** [comment]
* 8e565d958920f5cf27a3726d5bc140243befdac8  Add scan-build target to Makefile 
* a5b36385f49220504ce6de504862805811a6d83e  Remove dead stores found by clang scan build 

The above commits should 1) enable running the clang static analyzer via "make scan-build", and 2) remove the dead stores that it detected.
