### ISSUE TITLE
Visual Studio 2013 fails to compile.

### ISSUE THREAD

**Issue by VallentinSource** [smcameron/open-simplex-noise-in-c#5]
When compiling the following error is generated.

```
Error	1	error C2054: expected '(' to follow 'inline'	open-simplex-noise.c	131	1
Error	2	error C2085: 'fastFloor' : not in formal parameter list	open-simplex-noise.c	131	1
Error	3	error C2143: syntax error : missing ';' before '{'	open-simplex-noise.c	131	1
Warning	4	warning C4013: 'fastFloor' undefined; assuming extern returning int	open-simplex-noise.c	239	1
```

*Various personal info omitted from the above error messages!*

**Comment by smcameron** [comment]
Hello.  A couple points:

1)  I do not have any windows machine, so I cannot try out any attempted fix.
2) I have just started a new job, and the open source policies are, let's say, a bit onerous.  It will be at least 30 days before I can do anything anyway.
3) I suggest someone fork the project and carry on without me.

**Comment by davegorst** [comment]
This should be fixed now.
